=== YoshiRotar/XMLProject/Stage 1/structure.dtd
<!ELEMENT Project (Head,Collection)>

<!ELEMENT Head (Author+,Title)>

<!ELEMENT Collection (Albums,Artists,Genres)>

<!ELEMENT Author (#PCDATA)>
<!ATTLIST Author index CDATA #REQUIRED>

<!ELEMENT Albums (Album)+>

<!ELEMENT Artists (Artist)+>

<!ELEMENT Genres (Genre)+>

<!ELEMENT Album (Title,NumberOfRecords,Length,ReleaseDate)>
<!ATTLIST Album idArtist IDREF #REQUIRED
				idGenre IDREFS #REQUIRED>

<!ELEMENT Artist (BandName,Member+)>
<!ATTLIST Artist idArtist ID #REQUIRED
				 nationality (USA | GBR | SWE | POL | DEU) #IMPLIED>

<!ELEMENT Genre (#PCDATA)>
<!ATTLIST Genre idGenre ID #REQUIRED>

<!ELEMENT Length (#PCDATA)>

<!ELEMENT ReleaseDate (#PCDATA)>

<!ELEMENT BandName (#PCDATA)>

<!ELEMENT Member (#PCDATA)>

<!ELEMENT Title (#PCDATA)>

<!ELEMENT NumberOfRecords (#PCDATA)>

=== YoshiRotar/XMLProject/Stage 1/core.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Project SYSTEM "structure.dtd">
<Project>
	<Head>
		<Author index="210278"> Paweł Młynarczyk </Author>
		<Author index="210245"> Mateusz Kuźniarek </Author>
		<Title> Kolekcja Albumów Muzycznych </Title>
	</Head>
	<Collection>
		<Albums>
			<Album idArtist="A12" idGenre="G6">
				<Title> 10,000 Days </Title>
				<Length> 75:52 </Length>
				<ReleaseDate> 28.04.2006 </ReleaseDate>
			</Album>
			<Album idArtist="A10" idGenre="G8">
				<Title> .5: The Gray Chapter </Title>
				<Length> 63:51 </Length>
				<ReleaseDate> 17.10.2014 </ReleaseDate>
			</Album>
			<Album idArtist="A12" idGenre="G6">
				<Title> Aenima </Title>
				<Length> 77:18 </Length>
				<ReleaseDate> 17.09.1996 </ReleaseDate>
			</Album>
			<Album idArtist="A10" idGenre="G8">
				<Title> All Hope Is Gone </Title>
				<Length> 57:57 </Length>
				<ReleaseDate> 20.08.2008 </ReleaseDate>
			</Album>
			<Album idArtist="A5" idGenre="G1">
				<Title> Anthem Of The Peaceful Army </Title>
				<Length> 45:53 </Length>
				<ReleaseDate> 19.10.2018 </ReleaseDate>
			</Album>
			<Album idArtist="A2" idGenre="G11">
				<Title> The Apostasy </Title>
				<Length> 39:39 </Length>
				<ReleaseDate> 17.07.2007 </ReleaseDate>
			</Album>
			<Album idArtist="A1" idGenre="G7">
				<Title> Avatar Country </Title>
				<Length> 43:18 </Length>
				<ReleaseDate> 12.01.2018 </ReleaseDate>
			</Album>
			<Album idArtist="A9" idGenre="G4">
				<Title> Bible Of The Beast </Title>
				<Length> 47:36 </Length>
				<ReleaseDate> 24.04.2009 </ReleaseDate>
			</Album>
			<Album idArtist="A3" idGenre="G5">
				<Title> Black Sabbath </Title>
				<Length> 38:12 </Length>
				<ReleaseDate> 13.02.1970 </ReleaseDate>
			</Album>
			<Album idArtist="A1" idGenre="G10">
				<Title> Black Waltz </Title>
				<Length> Black Waltz </Length>
				<ReleaseDate> 25.01.2012 </ReleaseDate>
			</Album>
			<Album idArtist="A9" idGenre="G4">
				<Title> Blessed &amp; Possessed </Title>
				<Length> 45:42 </Length>
				<ReleaseDate> 17.07.2015 </ReleaseDate>
			</Album>
			<Album idArtist="A9" idGenre="G4">
				<Title> Blood Of The Saints </Title>
				<Length> 41:46 </Length>
				<ReleaseDate> 29.07.2011 </ReleaseDate>
			</Album>
			<Album idArtist="A6" idGenre="G5">
				<Title> The Book Of Souls </Title>
				<Length> 92:11 </Length>
				<ReleaseDate> 4.09.2015 </ReleaseDate>
			</Album>
			<Album idArtist="A3" idGenre="G5">
				<Title> Born Again </Title>
				<Length> 41:04 </Length>
				<ReleaseDate> 7.08.1983 </ReleaseDate>
			</Album>
			<Album idArtist="A6" idGenre="G5">
				<Title> Brave New World </Title>
				<Length> 66:57 </Length>
				<ReleaseDate> 29.05.2000 </ReleaseDate>
			</Album>
			<Album idArtist="A3" idGenre="G5">
				<Title> Cross Purposes </Title>
				<Length> 47:27 </Length>
				<ReleaseDate> 26.01.1994 </ReleaseDate>
			</Album>
			<Album idArtist="A8" idGenre="G3">
				<Title> Eat The Elephant </Title>
				<Length> 57:07 </Length>
				<ReleaseDate> 20.04.2018 </ReleaseDate>
			</Album>
			<Album idArtist="A8" idGenre="G3">
				<Title> eMOTIVe </Title>
				<Length> 48:13 </Length>
				<ReleaseDate> 1.11.2004 </ReleaseDate>
			</Album>
			<Album idArtist="A3" idGenre="G5">
				<Title> The Eternal Idol </Title>
				<Length> 42:42 </Length>
				<ReleaseDate> 23.11.1987 </ReleaseDate>
			</Album>
			<Album idArtist="A2" idGenre="G11">
				<Title> Evangelion </Title>
				<Length> 41:54 </Length>
				<ReleaseDate> 7.08.2009 </ReleaseDate>
			</Album>
			<Album idArtist="A7" idGenre="G12">
				<Title> Exercises In Futility </Title>
				<Length> 42:12 </Length>
				<ReleaseDate> 4.09.2015 </ReleaseDate>
			</Album>
			<Album idArtist="A6" idGenre="G5">
				<Title> Fear Of The Dark </Title>
				<Length> 57:58 </Length>
				<ReleaseDate> 11.05.1992 </ReleaseDate>
			</Album>
			<Album idArtist="A1" idGenre="G7">
				<Title> Feathers &amp; Flesh </Title>
				<Length> 67:51 </Length>
				<ReleaseDate> 13.05.2016 </ReleaseDate>
			</Album>
			<Album idArtist="A5" idGenre="G1">
				<Title> From The Fires </Title>
				<Length> 32:15 </Length>
				<ReleaseDate> 10.11.2017 </ReleaseDate>
			</Album>
			<Album idArtist="A1" idGenre="G10">
				<Title> Hail The Apocalypse </Title>
				<Length> 50:52 </Length>
				<ReleaseDate> 13.05.2014 </ReleaseDate>
			</Album>
			<Album idArtist="A3" idGenre="G5">
				<Title> Headless Cross </Title>
				<Length> 40:24 </Length>
				<ReleaseDate> 24.04.1989 </ReleaseDate>
			</Album>
			<Album idArtist="A3" idGenre="G5">
				<Title> Heaven And Hell </Title>
				<Length> 39:46 </Length>
				<ReleaseDate> 25.04.1980 </ReleaseDate>
			</Album>
			<Album idArtist="A11" idGenre="G3">
				<Title> Hypnotize </Title>
				<Length> 39:40 </Length>
				<ReleaseDate> 22.11.2005 </ReleaseDate>
			</Album>
			<Album idArtist="A2" idGenre="G11">
				<Title> I Loved You At Your Darkest </Title>
				<Length> 46:32 </Length>
				<ReleaseDate> 5.10.2018 </ReleaseDate>
			</Album>
			<Album idArtist="A4" idGenre="G2">
				<Title> If You Have Ghost </Title>
				<Length> 24:41 </Length>
				<ReleaseDate> 20.11.2013 </ReleaseDate>
			</Album>
			<Album idArtist="A4" idGenre="G9">
				<Title> Infestissumam </Title>
				<Length> 47:47 </Length>
				<ReleaseDate> 10.04.2013 </ReleaseDate>
			</Album>
			<Album idArtist="A10" idGenre="G8">
				<Title> Iowa </Title>
				<Length> 66:19 </Length>
				<ReleaseDate> 28.08.2001 </ReleaseDate>
			</Album>
			<Album idArtist="A12" idGenre="G6">
				<Title> Lateralus </Title>
				<Length> 78:56 </Length>
				<ReleaseDate> 15.05.2001 </ReleaseDate>
			</Album>
			<Album idArtist="A9" idGenre="G4">
				<Title> Lupus Dei </Title>
				<Length> 43:31 </Length>
				<ReleaseDate> 7.05.2007 </ReleaseDate>
			</Album>
			<Album idArtist="A3" idGenre="G5">
				<Title> Master Of Reality </Title>
				<Length> 34:29 </Length>
				<ReleaseDate> 21.07.1971 </ReleaseDate>
			</Album>
			<Album idArtist="A6" idGenre="G5">
				<Title> A Matter Of Life And Death </Title>
				<Length> 71:53 </Length>
				<ReleaseDate> 25.08.2006 </ReleaseDate>
			</Album>
			<Album idArtist="A4" idGenre="G9">
				<Title> Meliora </Title>
				<Length> 41:35 </Length>
				<ReleaseDate> 21.08.2015 </ReleaseDate>
			</Album>
			<Album idArtist="A8" idGenre="G3">
				<Title> Mer De Noms </Title>
				<Length> 44:25 </Length>
				<ReleaseDate> 23.05.2000 </ReleaseDate>
			</Album>
			<Album idArtist="A11" idGenre="G3">
				<Title> Mezmerize </Title>
				<Length> 36:06 </Length>
				<ReleaseDate> 17.05.2005 </ReleaseDate>
			</Album>
			<Album idArtist="A3" idGenre="G5">
				<Title> Mob Rules </Title>
				<Length> 40:25 </Length>
				<ReleaseDate> 4.11.1981 </ReleaseDate>
			</Album>
			<Album idArtist="A6" idGenre="G5">
				<Title> The Number Of The Beast </Title>
				<Length> 39:11 </Length>
				<ReleaseDate> 22.03.1982 </ReleaseDate>
			</Album>
			<Album idArtist="A4" idGenre="G9">
				<Title> Opus Eponymous </Title>
				<Length> 34:41 </Length>
				<ReleaseDate> 18.10.2010 </ReleaseDate>
			</Album>
			<Album idArtist="A3" idGenre="G5">
				<Title> Paranoid </Title>
				<Length> 41:51 </Length>
				<ReleaseDate> 18.09.1970 </ReleaseDate>
			</Album>
			<Album idArtist="A6" idGenre="G5">
				<Title> Piece Of Mind </Title>
				<Length> 45:18 </Length>
				<ReleaseDate> 16.05.1983 </ReleaseDate>
			</Album>
			<Album idArtist="A4" idGenre="G2">
				<Title> Popestar </Title>
				<Length> 23:37 </Length>
				<ReleaseDate> 16.09.2016 </ReleaseDate>
			</Album>
			<Album idArtist="A6" idGenre="G5">
				<Title> Powerslave </Title>
				<Length> 51:12 </Length>
				<ReleaseDate> 3.09.1984 </ReleaseDate>
			</Album>
			<Album idArtist="A9" idGenre="G4">
				<Title> Preachers Of The Night </Title>
				<Length> 45:32 </Length>
				<ReleaseDate> 19.07.2013 </ReleaseDate>
			</Album>
			<Album idArtist="A4" idGenre="G2">
				<Title> Prequelle </Title>
				<Length> 41:43 </Length>
				<ReleaseDate> 1.06.2018 </ReleaseDate>
			</Album>
			<Album idArtist="A9" idGenre="G4">
				<Title> Return In Bloodred </Title>
				<Length> 40:00 </Length>
				<ReleaseDate> 4.04.2005 </ReleaseDate>
			</Album>
			<Album idArtist="A9" idGenre="G4">
				<Title> The Sacrament Of Sin </Title>
				<Length> 42:42 </Length>
				<ReleaseDate> 20.07.2018 </ReleaseDate>
			</Album>
			<Album idArtist="A2" idGenre="G11">
				<Title> The Satanist </Title>
				<Length> 44:17 </Length>
				<ReleaseDate> 3.02.2014 </ReleaseDate>
			</Album>
			<Album idArtist="A10" idGenre="G8">
				<Title> Slipknot </Title>
				<Length> 60:26 </Length>
				<ReleaseDate> 29.06.1999 </ReleaseDate>
			</Album>
			<Album idArtist="A11" idGenre="G3">
				<Title> Steal This Album! </Title>
				<Length> 43:22 </Length>
				<ReleaseDate> 26.11.2002 </ReleaseDate>
			</Album>
			<Album idArtist="A11" idGenre="G3">
				<Title> System Of A Down </Title>
				<Length> 40:36 </Length>
				<ReleaseDate> 30.06.1998 </ReleaseDate>
			</Album>
			<Album idArtist="A8" idGenre="G3">
				<Title> Thirteenth Step </Title>
				<Length> 50:36 </Length>
				<ReleaseDate> 16.09.2003 </ReleaseDate>
			</Album>
			<Album idArtist="A11" idGenre="G3">
				<Title> Toxicity </Title>
				<Length> 44:01 </Length>
				<ReleaseDate> 27.08.2001 </ReleaseDate>
			</Album>
			<Album idArtist="A3" idGenre="G5">
				<Title> Tyr </Title>
				<Length> 39:16 </Length>
				<ReleaseDate> 20.08.1990 </ReleaseDate>
			</Album>
			<Album idArtist="A12" idGenre="G6">
				<Title> Undertow </Title>
				<Length> 69:13 </Length>
				<ReleaseDate> 6.04.1993 </ReleaseDate>
			</Album>
			<Album idArtist="A10" idGenre="G8">
				<Title> Vol.3: (The Subliminal Verses) </Title>
				<Length> 60:09 </Length>
				<ReleaseDate> 21.05.2004 </ReleaseDate>
			</Album>
		</Albums>
		<Artists>
			<Artist idArtist="A1" nationality="SWE">
				<BandName> Avatar </BandName>
				<Member> Jonas "Kungen" Jarlsby </Member>
				<Member> John Alfredsson </Member>
				<Member> Johannes Eckerström </Member>
				<Member> Tim Öhrström </Member>
