=== YoshiRotar/XMLProject/Stage 5/src/main/resources/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:mc="urn:musicCollection" targetNamespace="urn:musicCollection">
	<xsd:element name="Project" type="mc:ProjectType">
		<xsd:key name="ArtistKey">
			<xsd:selector xpath="Collection/Artists/Artist"/>
			<xsd:field xpath="@idArtist"/>
		</xsd:key>
		<xsd:key name="GenreKey">
			<xsd:selector xpath="Collection/Genres/Genre"/>
			<xsd:field xpath="@idGenre"/>
		</xsd:key>
		<xsd:keyref name="ArtistRef" refer="mc:ArtistKey">
			<xsd:selector xpath="Collection/Albums/Album"/>
			<xsd:field xpath="@idArtist"/>
		</xsd:keyref>
	</xsd:element>
	<xsd:complexType name="ProjectType">
		<xsd:sequence>
			<xsd:element name="Head" type="mc:HeadType"/>
			<xsd:element name="Collection" type="mc:CollectionType"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="HeadType">
		<xsd:sequence>
			<xsd:element name="Author" type="mc:AuthorType" maxOccurs="2"/>
			<xsd:element name="Title" type="xsd:normalizedString" fixed="Kolekcja Albumów Muzycznych"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="AuthorType">
		<xsd:sequence>
			<xsd:element name="Name" type="mc:NameType"/>
			<xsd:element name="Surname" type="mc:NameType"/>
		</xsd:sequence>
		<xsd:attribute name="index" type="mc:IndexType" use="required"/>
	</xsd:complexType>
	<xsd:simpleType name="NameType">
		<xsd:restriction base="xsd:token">
			<xsd:pattern value="[A-ZŻÖ]{1}[a-ząćęłńóśźżö]+"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="IndexType">
		<xsd:restriction base="xsd:positiveInteger">
			<xsd:minInclusive value="100000"/>
			<xsd:maxExclusive value="1000000"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name="CollectionType">
		<xsd:sequence>
			<xsd:element name="Albums" type="mc:AlbumsType"/>
			<xsd:element name="Artists" type="mc:ArtistsType"/>
			<xsd:element name="Genres" type="mc:GenresType"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="AlbumsType">
		<xsd:sequence>
			<xsd:element name="Album" type="mc:AlbumType" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="AlbumType">
		<xsd:sequence>
			<xsd:element name="Title" type="xsd:normalizedString"/>
			<xsd:element name="NumberOfTracks" type="xsd:positiveInteger"/>
			<xsd:element name="Length" type="xsd:time"/>
			<xsd:element name="ReleaseDate" type="xsd:date"/>
		</xsd:sequence>
		<xsd:attribute name="idArtist" type="xsd:IDREF" use="required"/>
		<xsd:attribute name="idGenre" type="xsd:IDREFS"/>
	</xsd:complexType>
	<xsd:complexType name="ArtistsType">
		<xsd:sequence>
			<xsd:element name="Artist" type="mc:ArtistType" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="ArtistType">
		<xsd:sequence>
			<xsd:element name="BandName" type="xsd:normalizedString"/>
			<xsd:element name="Member" type="mc:MemberType" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="idArtist" type="xsd:ID" use="required"/>
		<xsd:attribute name="nationality" type="mc:NationalityType"/>
	</xsd:complexType>
	<xsd:complexType name="MemberType">
		<xsd:choice maxOccurs="unbounded">
			<xsd:group ref="mc:RealName"/>
			<xsd:element name="StageName" type="xsd:normalizedString" maxOccurs="unbounded"/>
		</xsd:choice>
		<xsd:attribute name="frontman" type="xsd:boolean" default="false"/>
	</xsd:complexType>
	<xsd:group name="RealName">
		<xsd:sequence>
			<xsd:element name="Name" type="mc:NameType" maxOccurs="2"/>
			<xsd:element name="Surname" type="mc:MemberSurnameType"/>
		</xsd:sequence>
	</xsd:group>
	<xsd:simpleType name="MemberSurnameType">
		<xsd:union memberTypes="mc:NameType mc:ForeignSurnameType"/>
	</xsd:simpleType>
	<xsd:simpleType name="ForeignSurnameType">
		<xsd:restriction base="xsd:token">
			<xsd:pattern value="[a-z]{3} [A-ZŻÖ][a-zö]+"/>
			<xsd:pattern value="[A-ZŻÖ][a-zöA-ZŻÖ]+"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="NationalityType">
		<xsd:restriction base="xsd:NMTOKEN">
			<xsd:enumeration value="SWE"/>
			<xsd:enumeration value="POL"/>
			<xsd:enumeration value="GBR"/>
			<xsd:enumeration value="USA"/>
			<xsd:enumeration value="DEU"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name="GenresType">
		<xsd:sequence>
			<xsd:element name="Genre" type="mc:GenreType" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="GenreType">
		<xsd:simpleContent>
			<xsd:extension base="xsd:normalizedString">
				<xsd:attribute name="idGenre" type="xsd:ID" use="required"/>
			</xsd:extension>
		</xsd:simpleContent>
	</xsd:complexType>
</xsd:schema>

=== YoshiRotar/XMLProject/Stage 2/core.xml
<?xml version="1.0" encoding="UTF-8"?>
<mc:Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="urn:musicCollection schema.xsd" 
		 xmlns:mc="urn:musicCollection">
	<Head>
		<Author index="210278">
			<Name> Paweł </Name>
			<Surname> Młynarczyk </Surname>  
		</Author>
		<Author index="210245">
			<Name> Mateusz </Name>
			<Surname> Kuźniarek </Surname>   
		</Author>
		<Title> Kolekcja Albumów Muzycznych </Title>
	</Head>
	<Collection>
		<Albums>
			<Album idArtist="A12" idGenre="G18">
				<Title> 10,000 Days </Title>
				<NumberOfTracks> 11 </NumberOfTracks>
				<Length> 01:15:52 </Length>
				<ReleaseDate> 2006-04-28 </ReleaseDate>
			</Album>
			<Album idArtist="A10" idGenre="G11 G14">
				<Title> .5: The Gray Chapter </Title>
				<NumberOfTracks> 14 </NumberOfTracks>
				<Length> 01:03:51 </Length>
				<ReleaseDate> 2014-10-17 </ReleaseDate>
			</Album>
			<Album idArtist="A12" idGenre="G1 G18">
				<Title> Aenima </Title>
				<NumberOfTracks> 15 </NumberOfTracks>
				<Length> 01:17:18 </Length>
				<ReleaseDate> 1996-09-17 </ReleaseDate>
			</Album>
			<Album idArtist="A10" idGenre="G9">
				<Title> All Hope Is Gone </Title>
				<NumberOfTracks> 12 </NumberOfTracks>
				<Length> 00:57:57 </Length>
				<ReleaseDate> 2008-08-20 </ReleaseDate>
			</Album>
			<Album idArtist="A5" idGenre="G10 G7 G19">
				<Title> Anthem Of The Peaceful Army </Title>
				<NumberOfTracks> 10 </NumberOfTracks>
				<Length> 00:45:53 </Length>
				<ReleaseDate> 2018-10-19 </ReleaseDate>
			</Album>
			<Album idArtist="A2" idGenre="G6">
				<Title> The Apostasy </Title>
				<NumberOfTracks> 13 </NumberOfTracks>
				<Length> 00:39:39 </Length>
				<ReleaseDate> 2007-07-17 </ReleaseDate>
			</Album>
			<Album idArtist="A1" idGenre="G11">
				<Title> Avatar Country </Title>
				<NumberOfTracks> 10 </NumberOfTracks>
				<Length> 00:43:18 </Length>
				<ReleaseDate> 2018-01-12 </ReleaseDate>
			</Album>
			<Album idArtist="A9" idGenre="G16 G11">
				<Title> Bible Of The Beast </Title>
				<NumberOfTracks> 12 </NumberOfTracks>
				<Length> 00:47:36 </Length>
				<ReleaseDate> 2009-04-24 </ReleaseDate>
			</Album>
			<Album idArtist="A3" idGenre="G11">
				<Title> Black Sabbath </Title>
				<NumberOfTracks> 7 </NumberOfTracks>
				<Length> 00:38:12 </Length>
				<ReleaseDate> 1970-02-13 </ReleaseDate>
			</Album>
			<Album idArtist="A1" idGenre="G9 G13 G4 G12">
				<Title> Black Waltz </Title>
				<NumberOfTracks> 11 </NumberOfTracks>
				<Length> 00:54:48 </Length>
				<ReleaseDate> 2012-01-25 </ReleaseDate>
			</Album>
			<Album idArtist="A9" idGenre="G16 G20">
				<Title> Blessed &amp; Possessed </Title>
				<NumberOfTracks> 11 </NumberOfTracks>
				<Length> 00:45:42 </Length>
				<ReleaseDate> 2015-07-17 </ReleaseDate>
			</Album>
			<Album idArtist="A9" idGenre="G16 G11">
				<Title> Blood Of The Saints </Title>
				<NumberOfTracks> 11 </NumberOfTracks>
				<Length> 00:41:46 </Length>
				<ReleaseDate> 2011-07-29 </ReleaseDate>
			</Album>
			<Album idArtist="A6" idGenre="G11">
				<Title> The Book Of Souls </Title>
				<NumberOfTracks> 11 </NumberOfTracks>
				<Length> 01:32:11 </Length>
				<ReleaseDate> 2015-09-04 </ReleaseDate>
			</Album>
			<Album idArtist="A3" idGenre="G11">
				<Title> Born Again </Title>
				<NumberOfTracks> 9 </NumberOfTracks>
				<Length> 00:41:04 </Length>
				<ReleaseDate> 1983-08-07 </ReleaseDate>
			</Album>
			<Album idArtist="A6" idGenre="G11">
				<Title> Brave New World </Title>
				<NumberOfTracks> 10 </NumberOfTracks>
				<Length> 01:06:57 </Length>
				<ReleaseDate> 2000-05-29 </ReleaseDate>
			</Album>
			<Album idArtist="A3" idGenre="G11">
				<Title> Cross Purposes </Title>
				<NumberOfTracks> 11 </NumberOfTracks>
				<Length> 00:47:27 </Length>
				<ReleaseDate> 1994-01-26 </ReleaseDate>
			</Album>
			<Album idArtist="A8" idGenre="G19 G15 G10">
				<Title> Eat The Elephant </Title>
				<NumberOfTracks> 12 </NumberOfTracks>
				<Length> 00:57:07 </Length>
				<ReleaseDate> 2018-04-20 </ReleaseDate>
			</Album>
			<Album idArtist="A8" idGenre="G2 G3">
				<Title> eMOTIVe </Title>
				<NumberOfTracks> 12 </NumberOfTracks>
				<Length> 00:48:13 </Length>
				<ReleaseDate> 2004-11-01 </ReleaseDate>
			</Album>
			<Album idArtist="A3" idGenre="G11">
				<Title> The Eternal Idol </Title>
				<NumberOfTracks> 9 </NumberOfTracks>
				<Length> 00:42:42 </Length>
				<ReleaseDate> 1987-11-23 </ReleaseDate>
			</Album>
			<Album idArtist="A2" idGenre="G6 G17 G21">
				<Title> Evangelion </Title>
				<NumberOfTracks> 10 </NumberOfTracks>
				<Length> 00:41:54 </Length>
				<ReleaseDate> 2009-08-07 </ReleaseDate>
			</Album>
			<Album idArtist="A7" idGenre="G5">
				<Title> Exercises In Futility </Title>
				<NumberOfTracks> 6 </NumberOfTracks>
				<Length> 00:42:12 </Length>
				<ReleaseDate> 2015-09-04 </ReleaseDate>
			</Album>
			<Album idArtist="A6" idGenre="G11">
				<Title> Fear Of The Dark </Title>
				<NumberOfTracks> 12 </NumberOfTracks>
				<Length> 00:57:58 </Length>
				<ReleaseDate> 1992-05-11 </ReleaseDate>
			</Album>
			<Album idArtist="A1" idGenre="G9 G13 G4 G11">
				<Title> Feathers &amp; Flesh </Title>
				<NumberOfTracks> 14 </NumberOfTracks>
				<Length> 01:07:51 </Length>
				<ReleaseDate> 2016-05-13 </ReleaseDate>
			</Album>
			<Album idArtist="A5" idGenre="G10 G7">
				<Title> From The Fires </Title>
				<NumberOfTracks> 8 </NumberOfTracks>
				<Length> 00:32:15 </Length>
				<ReleaseDate> 2017-11-10 </ReleaseDate>
			</Album>
			<Album idArtist="A1" idGenre="G9 G13 G12 G18">
				<Title> Hail The Apocalypse </Title>
				<NumberOfTracks> 12 </NumberOfTracks>
				<Length> 00:50:52 </Length>
				<ReleaseDate> 2014-05-13 </ReleaseDate>
			</Album>
			<Album idArtist="A3" idGenre="G11 G8">
				<Title> Headless Cross </Title>
				<NumberOfTracks> 9 </NumberOfTracks>
				<Length> 00:40:24 </Length>
				<ReleaseDate> 1989-04-24 </ReleaseDate>
			</Album>
			<Album idArtist="A3" idGenre="G11">
				<Title> Heaven And Hell </Title>
				<NumberOfTracks> 8 </NumberOfTracks>
				<Length> 00:39:46 </Length>
				<ReleaseDate> 1980-04-25 </ReleaseDate>
			</Album>
			<Album idArtist="A11" idGenre="G11 G10">
				<Title> Hypnotize </Title>
				<NumberOfTracks> 12 </NumberOfTracks>
				<Length> 00:39:40 </Length>
				<ReleaseDate> 2005-11-22 </ReleaseDate>
			</Album>
			<Album idArtist="A2" idGenre="G6 G17 G21">
				<Title> I Loved You At Your Darkest </Title>
				<NumberOfTracks> 13 </NumberOfTracks>
				<Length> 00:46:32 </Length>
				<ReleaseDate> 2018-10-05 </ReleaseDate>
			</Album>
			<Album idArtist="A4" idGenre="G11 G8">
				<Title> If You Have Ghost </Title>
				<NumberOfTracks> 5 </NumberOfTracks>
				<Length> 00:24:41 </Length>
				<ReleaseDate> 2013-11-20 </ReleaseDate>
			</Album>
			<Album idArtist="A4" idGenre="G11 G8 G19">
				<Title> Infestissumam </Title>
				<NumberOfTracks> 10 </NumberOfTracks>
				<Length> 00:47:47 </Length>
				<ReleaseDate> 2013-04-10 </ReleaseDate>
			</Album>
			<Album idArtist="A10" idGenre="G14">
				<Title> Iowa </Title>
				<NumberOfTracks> 14 </NumberOfTracks>
				<Length> 01:06:19 </Length>
				<ReleaseDate> 2001-08-28 </ReleaseDate>
			</Album>
			<Album idArtist="A12" idGenre="G18 G19">
				<Title> Lateralus </Title>
				<NumberOfTracks> 13 </NumberOfTracks>
				<Length> 01:18:56 </Length>
				<ReleaseDate> 2001-05-15 </ReleaseDate>
			</Album>
			<Album idArtist="A9" idGenre="G16 G11">
				<Title> Lupus Dei </Title>
				<NumberOfTracks> 11 </NumberOfTracks>
				<Length> 00:43:31 </Length>
				<ReleaseDate> 2007-05-07 </ReleaseDate>
			</Album>
			<Album idArtist="A3" idGenre="G11">
				<Title> Master Of Reality </Title>
				<NumberOfTracks> 8 </NumberOfTracks>
				<Length> 00:34:29 </Length>
				<ReleaseDate> 1971-07-21 </ReleaseDate>
			</Album>
			<Album idArtist="A6" idGenre="G11">
				<Title> A Matter Of Life And Death </Title>
				<NumberOfTracks> 10 </NumberOfTracks>
				<Length> 01:11:53 </Length>
				<ReleaseDate> 2006-08-25 </ReleaseDate>
			</Album>
			<Album idArtist="A4" idGenre="G11 G8 G19 G10">
				<Title> Meliora </Title>
				<NumberOfTracks> 10 </NumberOfTracks>
				<Length> 00:41:35 </Length>
				<ReleaseDate> 2015-08-21 </ReleaseDate>
			</Album>
			<Album idArtist="A8" idGenre="G1 G2 G10 G19 G3">
				<Title> Mer De Noms </Title>
				<NumberOfTracks> 12 </NumberOfTracks>
				<Length> 00:44:25 </Length>
				<ReleaseDate> 2000-05-23 </ReleaseDate>
			</Album>
			<Album idArtist="A11" idGenre="G14">
				<Title> Mezmerize </Title>
				<NumberOfTracks> 11 </NumberOfTracks>
				<Length> 00:36:06 </Length>
				<ReleaseDate> 2005-05-17 </ReleaseDate>
			</Album>
			<Album idArtist="A3" idGenre="G11">
				<Title> Mob Rules </Title>
				<NumberOfTracks> 9 </NumberOfTracks>
				<Length> 00:40:25 </Length>
				<ReleaseDate> 1981-11-04 </ReleaseDate>
			</Album>
			<Album idArtist="A6" idGenre="G11">
				<Title> The Number Of The Beast </Title>
				<NumberOfTracks> 9 </NumberOfTracks>
				<Length> 00:44:39 </Length>
				<ReleaseDate> 1982-03-22 </ReleaseDate>
			</Album>
			<Album idArtist="A4" idGenre="G11 G8 G10">
				<Title> Opus Eponymous </Title>
				<NumberOfTracks> 9 </NumberOfTracks>
				<Length> 00:34:41 </Length>
				<ReleaseDate> 2010-10-18 </ReleaseDate>
			</Album>
			<Album idArtist="A3" idGenre="G11">
				<Title> Paranoid </Title>
				<NumberOfTracks> 8 </NumberOfTracks>
				<Length> 00:41:51 </Length>
				<ReleaseDate> 1970-09-18 </ReleaseDate>
			</Album>
			<Album idArtist="A6" idGenre="G11">
				<Title> Piece Of Mind </Title>
				<NumberOfTracks> 9 </NumberOfTracks>
				<Length> 00:45:18 </Length>
				<ReleaseDate> 1983-05-16 </ReleaseDate>
			</Album>
			<Album idArtist="A4" idGenre="G11 G8 G10 G19">
				<Title> Popestar </Title>
				<NumberOfTracks> 5 </NumberOfTracks>
				<Length> 00:23:37 </Length>
				<ReleaseDate> 2016-09-16 </ReleaseDate>
			</Album>
			<Album idArtist="A6" idGenre="G11">
				<Title> Powerslave </Title>
				<NumberOfTracks> 8 </NumberOfTracks>
